export const QUERY_KEYS = {
    TODOS: 'TODOS',
} as const;

export const MUTATION_KEYS = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    CREATE_TODO: 'CREATE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO: 'DELETE_TODO',
    DELETE_MANY_TODOS: 'DELETE_MANY_TODOS',
    COMPLETE_MANY_TODOS: 'COMPLETE_MANY_TODOS',
} as const;